apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-token-reviewer
  namespace: infisical

---

apiVersion: v1
kind: Secret
metadata:
  name: infisical-token-reviewer-token
  namespace: infisical
  annotations:
    kubernetes.io/service-account.name: "infisical-token-reviewer"
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infisical-secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","create","update","patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infisical-token-reviewer-binding
roleRef:
  kind: ClusterRole
  name: infisical-secret-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: infisical-token-reviewer
    namespace: infisical

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-sa
  namespace: infisical

---

apiVersion: v1
kind: Secret
metadata:
  name: infisical-sa-token
  namespace: infisical
  annotations:
    kubernetes.io/service-account.name: "infisical-sa"
type: kubernetes.io/service-account-token
