apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.appSecret }}
  {{ $key }}: "{{ $value }}"
{{- end }}

